export const uiText = {
  id: {
    login: "Login",
    logout: "Keluar",
    languageLabel: "ID",
    languageTitle: "Ganti bahasa ke English US",
    localSimulation: "Simulasi lokal",
    physicalNfc: "NFC fisik",
    silentShield: "Silent Shield",
    headline: "Membership Benefit Card",
    intro:
      "Aplikasi operasional untuk daftar anggota, check-in, check-out, isi saldo, dan baca kartu koperasi.",
    cardMode: "Mode kartu",
    nfcReady: "NFC fisik siap",
    simulationRecommended: "Mode simulasi disarankan",
    simulation: "Simulasi",
    nfcPhysical: "NFC Fisik",
    simulationTitle: "Gunakan kartu simulasi lokal",
    resetCard: "Reset kartu",
    resetCardTitle: "Kosongkan kartu",
    noCard: "Belum ada kartu",
    balance: "Saldo",
    status: "Status",
    checkIn: "Check-in",
    savedLogs: "Log tersimpan",
    pendingWriteTitle: "Penulisan otomatis belum selesai",
    pendingWriteMessage:
      "Jika kartu sempat terangkat atau gagal ditulis otomatis, tekan tombol ini lalu tempelkan kartu NFC yang sama.",
    writeToNfc: "Tulis ke kartu NFC",
    navAdmin: "Admin",
    navEntry: "Masuk",
    navExit: "Keluar",
    navMember: "Anggota",
    adminTitle: "Admin Koperasi",
    adminDescription: "Daftarkan kartu baru, isi saldo, dan reset status kunjungan.",
    memberId: "ID Anggota",
    memberIdPlaceholder: "MBC001",
    name: "Nama",
    namePlaceholder: "Anggota Koperasi",
    initialBalance: "Saldo awal",
    initialBalancePlaceholder: "50000",
    savePhysicalCard: "Simpan ke kartu NFC",
    saveSimulatedCard: "Simpan kartu simulasi",
    topUpBalance: "Isi saldo",
    topUpPlaceholder: "25000",
    resetOut: "Reset status keluar",
    encryptedData: "Data terenkripsi",
    encryptedDescription: "Data yang tersimpan di kartu tidak dapat dibaca langsung.",
    noCardPayload: "Belum ada kartu.",
    entryTitle: "Pintu Masuk",
    entryDescription: "Tempel kartu untuk mengubah status dari keluar menjadi masuk.",
    simulationTimeMode: "Mode simulasi waktu",
    simulationTimeHelp: "Atur waktu check-in ke masa lalu untuk uji tarif.",
    checkInTime: "Waktu check-in",
    readingCard: "Membaca kartu...",
    entryValidation: "Validasi pintu masuk",
    mustBeRegistered: "Kartu wajib sudah terdaftar.",
    mustBeOut: "Status harus keluar sebelum check-in.",
    repeatedCheckInRejected: "Check-in berulang akan ditolak.",
    exitTitle: "Pintu Keluar",
    exitDescription: "Hitung tarif Rp2.000 per jam dengan pembulatan ke atas.",
    entryTime: "Masuk",
    tariff: "Tarif",
    checkOutCharge: "Check-out dan potong saldo",
    exitValidation: "Validasi pintu keluar",
    mustBeIn: "Status harus masuk sebelum check-out.",
    roundedDuration: "Durasi dibulatkan ke atas per jam.",
    insufficientBalanceHint:
      "Jika saldo tidak cukup, anggota diarahkan ke Admin Koperasi untuk isi saldo.",
    memberCardTitle: "Kartu Anggota",
    memberCardDescription: "Tampilan baca saja untuk anggota koperasi.",
    readPhysicalCard: "Baca kartu NFC",
    readSimulatedCard: "Baca kartu simulasi",
    lastUpdated: "Update terakhir",
    transactionHistory: "Riwayat transaksi",
    transactionHistoryDescription: "FIFO log, maksimal 5 transaksi terakhir.",
    type: "Tipe",
    amount: "Nominal",
    time: "Waktu",
    note: "Catatan",
    noTransactions: "Belum ada transaksi.",
    roleAccess: "Akses Petugas",
    roleLoginTitle: "Pilih peran pengguna",
    roleLoginDescription:
      "Pilih peran operasional. Setiap peran hanya membuka fitur yang sesuai dengan tanggung jawabnya.",
    enter: "Masuk",
    localSessionNote:
      "Demo ini memakai sesi lokal tanpa login server agar tetap bisa berjalan offline. Batas akses mengikuti peran: admin, pintu masuk, pintu keluar, dan anggota.",
    simulationActive: "Simulasi aktif",
    alternateModeAvailable: "Mode pengganti tersedia",
    simulationWorks:
      "Semua alur utama tetap bisa diuji di iPhone dengan kartu simulasi lokal.",
    nextRecommendation: "Rekomendasi berikutnya",
    qrRecommendation:
      "Tambahkan QR terenkripsi agar demo iPhone terasa lebih dekat dengan kartu fisik.",
    transactionRules: "Aturan utama sebelum transaksi diproses.",
    processingSimulation: "Memproses kartu simulasi",
    tapNfc: "Tempelkan kartu NFC",
    holdNfc: "Dekatkan kartu NFC ke perangkat dan tahan sampai transaksi selesai.",
    savingSimulation: "Membaca dan menyimpan data kartu simulasi.",
    transactionSuccess: "Transaksi berhasil",
    transactionFailed: "Transaksi gagal",
    resetNfcDone: "Kartu NFC dikosongkan",
    resetSimulationDone: "Kartu simulasi dikosongkan",
    restartFromAdmin:
      "Daftarkan kartu baru melalui menu Admin Koperasi untuk memulai ulang alur.",
    resetFailed: "Reset kartu gagal",
    detectedTitle: "Kartu NFC terdeteksi",
    detectedWithSerial: (serial: string) =>
      `Kartu terbaca dengan serial ${serial}. Tahan kartu sampai proses selesai.`,
    detectedNoSerial: "Kartu terbaca. Tahan kartu sampai proses selesai.",
    readFirstTitle: "Tempelkan kartu NFC untuk dibaca",
    readFirstMessage:
      "Aplikasi akan membaca kartu, menyiapkan perubahan, lalu langsung menulis ke kartu yang sama. Tahan kartu sampai muncul pesan berhasil.",
    updateReadyTitle: "Menulis perubahan ke kartu",
    updateReadyMessage:
      "Data kartu valid. Tetap tahan kartu di area NFC sampai proses tulis selesai.",
    prepareNfcFailed: "Gagal menyiapkan perubahan NFC",
    checkoutCardStillOut:
      "Kartu fisik yang dibaca masih berstatus OUT. Kemungkinan check-in sebelumnya belum ditulis ke kartu. Kembali ke peran Pintu Masuk, tekan Check-in, lalu wajib tekan Tulis ke kartu NFC sampai muncul pesan kartu berhasil disimpan.",
    noPendingWrite: "Belum ada perubahan untuk ditulis",
    prepareFirst: "Baca kartu dan siapkan transaksi terlebih dahulu.",
    writeNfcTitle: "Tempelkan kartu NFC untuk ditulis",
    writeSameCard: "Pastikan kartu yang ditempel adalah kartu yang baru dibaca.",
    writeNfcSuccess: "Kartu NFC berhasil disimpan",
    writeNfcSuccessMessage: "Perubahan sudah tersimpan ke kartu fisik.",
    writeNfcFailed: "Gagal menulis kartu NFC",
    nfcDialogEyebrow: "Mode NFC fisik",
    nfcDialogHelp:
      "Mode simulasi tetap bisa dipakai untuk menguji registrasi, check-in, check-out, top-up, dan baca kartu.",
    useSimulationMode: "Pakai simulasi",
    closeDialog: "Tutup",
    nfcNotDetectedTitle: "Kartu NFC tidak terdeteksi",
    nfcNotDetectedMessage:
      "Tempelkan kartu lebih dekat ke area NFC HP, tahan beberapa detik, lalu coba lagi. Pastikan NFC HP aktif dan kartu mendukung NDEF.",
    roleActive: (roleTitle: string) => `${roleTitle} aktif`,
    readOnlySuccess: "Kartu berhasil dibaca.",
  },
  en: {
    login: "Login",
    logout: "Logout",
    languageLabel: "EN",
    languageTitle: "Switch language to Bahasa Indonesia",
    localSimulation: "Local simulation",
    physicalNfc: "Physical NFC",
    silentShield: "Silent Shield",
    headline: "Membership Benefit Card",
    intro:
      "An operations app for member registration, check-in, check-out, balance top-up, and cooperative card lookup.",
    cardMode: "Card mode",
    nfcReady: "Physical NFC ready",
    simulationRecommended: "Simulation mode recommended",
    simulation: "Simulation",
    nfcPhysical: "Physical NFC",
    simulationTitle: "Use local simulated card",
    resetCard: "Reset card",
    resetCardTitle: "Clear card",
    noCard: "No card yet",
    balance: "Balance",
    status: "Status",
    checkIn: "Check-in",
    savedLogs: "Saved logs",
    pendingWriteTitle: "Automatic write did not finish",
    pendingWriteMessage:
      "If the card was moved away or automatic write failed, press this button and tap the same NFC card.",
    writeToNfc: "Write to NFC card",
    navAdmin: "Admin",
    navEntry: "Entry",
    navExit: "Exit",
    navMember: "Member",
    adminTitle: "Cooperative Admin",
    adminDescription: "Register a new card, add balance, and reset visit status.",
    memberId: "Member ID",
    memberIdPlaceholder: "MBC001",
    name: "Name",
    namePlaceholder: "Cooperative Member",
    initialBalance: "Initial balance",
    initialBalancePlaceholder: "50000",
    savePhysicalCard: "Save to NFC card",
    saveSimulatedCard: "Save simulated card",
    topUpBalance: "Add balance",
    topUpPlaceholder: "25000",
    resetOut: "Reset to checked out",
    encryptedData: "Encrypted data",
    encryptedDescription: "Card data is stored in encrypted form.",
    noCardPayload: "No card yet.",
    entryTitle: "Entry Gate",
    entryDescription: "Tap a card to change the status from checked out to checked in.",
    simulationTimeMode: "Time simulation mode",
    simulationTimeHelp: "Set check-in time in the past to test tariff calculation.",
    checkInTime: "Check-in time",
    readingCard: "Reading card...",
    entryValidation: "Entry validation",
    mustBeRegistered: "The card must already be registered.",
    mustBeOut: "Status must be checked out before check-in.",
    repeatedCheckInRejected: "Repeated check-in will be rejected.",
    exitTitle: "Exit Gate",
    exitDescription: "Calculate Rp2,000 per hour, rounded up.",
    entryTime: "Entry time",
    tariff: "Tariff",
    checkOutCharge: "Check-out and deduct balance",
    exitValidation: "Exit validation",
    mustBeIn: "Status must be checked in before check-out.",
    roundedDuration: "Duration is rounded up per hour.",
    insufficientBalanceHint:
      "If balance is insufficient, direct the member to Cooperative Admin for top-up.",
    memberCardTitle: "Member Card",
    memberCardDescription: "Read-only view for cooperative members.",
    readPhysicalCard: "Read NFC card",
    readSimulatedCard: "Read simulated card",
    lastUpdated: "Last updated",
    transactionHistory: "Transaction history",
    transactionHistoryDescription: "FIFO log, maximum 5 latest transactions.",
    type: "Type",
    amount: "Amount",
    time: "Time",
    note: "Note",
    noTransactions: "No transactions yet.",
    roleAccess: "Staff Access",
    roleLoginTitle: "Choose user role",
    roleLoginDescription:
      "Choose an operational role. Each role only unlocks features that match its responsibility.",
    enter: "Enter",
    localSessionNote:
      "This demo uses a local session without server login so it can still run offline. Access is limited by role: admin, entry gate, exit gate, and member.",
    simulationActive: "Simulation active",
    alternateModeAvailable: "Alternate mode available",
    simulationWorks:
      "All core flows can still be tested on iPhone with a local simulated card.",
    nextRecommendation: "Next recommendation",
    qrRecommendation:
      "Add encrypted QR support so the iPhone demo feels closer to a physical card.",
    transactionRules: "Main rules before the transaction is processed.",
    processingSimulation: "Processing simulated card",
    tapNfc: "Tap NFC card",
    holdNfc: "Hold the NFC card near the device until the transaction finishes.",
    savingSimulation: "Reading and saving simulated card data.",
    transactionSuccess: "Transaction successful",
    transactionFailed: "Transaction failed",
    resetNfcDone: "NFC card cleared",
    resetSimulationDone: "Simulated card cleared",
    restartFromAdmin: "Register a new card from Cooperative Admin to restart the flow.",
    resetFailed: "Failed to reset card",
    detectedTitle: "NFC card detected",
    detectedWithSerial: (serial: string) =>
      `Card detected with serial ${serial}. Keep holding it until the process finishes.`,
    detectedNoSerial: "Card detected. Keep holding it until the process finishes.",
    readFirstTitle: "Tap NFC card to read",
    readFirstMessage:
      "The app will read the card, prepare the update, then write to the same card automatically. Keep holding the card until it succeeds.",
    updateReadyTitle: "Writing update to card",
    updateReadyMessage:
      "The card data is valid. Keep holding the card near NFC until writing finishes.",
    prepareNfcFailed: "Failed to prepare NFC update",
    checkoutCardStillOut:
      "The physical card is still checked out. The previous check-in was probably not written to the card. Go back to Entry Gate, press Check-in, then press Write to NFC card until the card saved message appears.",
    noPendingWrite: "No update ready to write",
    prepareFirst: "Read the card and prepare a transaction first.",
    writeNfcTitle: "Tap NFC card to write",
    writeSameCard: "Make sure this is the same card that was just read.",
    writeNfcSuccess: "NFC card saved",
    writeNfcSuccessMessage: "The update has been saved to the physical card.",
    writeNfcFailed: "Failed to write NFC card",
    nfcDialogEyebrow: "Physical NFC mode",
    nfcDialogHelp:
      "Simulation mode can still test registration, check-in, check-out, top-up, and card lookup.",
    useSimulationMode: "Use simulation",
    closeDialog: "Close",
    nfcNotDetectedTitle: "NFC card was not detected",
    nfcNotDetectedMessage:
      "Move the card closer to the phone NFC area, hold it for a few seconds, then try again. Make sure phone NFC is enabled and the card supports NDEF.",
    roleActive: (roleTitle: string) => `${roleTitle} active`,
    readOnlySuccess: "Card read successfully.",
  },
} as const;

